services:
  main:
    image: server-image
    container_name: main
    depends_on:
      - secondary1
      - secondary2
    volumes:
      - ./target/replicated-log-main-1.0-SNAPSHOT.jar:/docker-dir/server.jar
      - ./docker-properties/server.properties:/docker-dir//properties/server.properties
    ports:
      - 8081:8080

  secondary1:
    image: secondary-image
    container_name: secondary1
    volumes:
      - ./target/replicated-log-secondary-1.0-SNAPSHOT.jar:/docker-dir/server.jar
      - ./docker-properties/server.properties:/docker-dir//properties/server.properties
    ports:
      - 8082:8080

  secondary2:
    image: secondary-image
    container_name: secondary2
    volumes:
      - ./target/replicated-log-secondary-1.0-SNAPSHOT.jar:/docker-dir/server.jar
      - ./docker-properties/server.properties:/docker-dir//properties/server.properties
    ports:
      - 8083:8080